BenCouwberghs/timeless_songs_frontend

src/app/app.routes.ts, src/app/band/component/band-information/band-information.component.html, src/app/band/component/band-information/band-information.component.spec.ts, src/app/band/component/band-information/band-information.component.ts, src/app/band/component/band-list/band-list.component.html, src/app/band/component/band-list/band-list.component.ts, src/app/band/component/new-band-form/new-band-form.component.ts, src/app/band/service/band.service.ts
Completed what's asked for in #12. Also created a BandService and refactored the http requests to be handled there, cleaning up the code of the components. Made sure to test everything.
=> Feature 12

src/app/band/component/band-information/band-information.component.html, src/app/band/component/band-information/band-information.component.ts, src/app/band/service/band.service.ts
=> Feature 13

src/app/band/component/band-list/band-list.component.html, src/app/band/component/band-list/band-list.component.ts, src/app/band/service/band.service.ts
=> Feature 16

src/app/band/component/band-information/band-information.component.ts, src/app/band/component/new-band-form/new-band-form.component.ts
Implementation of #18. Used alert() method.
=> Feature 18

.postcssrc.json, angular.json, package-lock.json, package.json, src/app/app.component.html, src/app/app.component.ts, src/app/app.config.ts, src/app/band/component/band-information/band-information.component.html, src/app/band/component/band-information/band-information.component.ts, src/app/band/component/band-list/band-list.component.html, src/app/band/component/band-list/band-list.component.ts, src/app/band/component/new-band-form/new-band-form.component.html, src/app/band/component/new-band-form/new-band-form.component.ts, src/index.html, src/styles.scss, src/tailwind.css
Big pull request
- upgrade to angular 20
- use PrimeNG
- use tailwind
- added menubar
- migrated new band component to PrimeNG
=> Feature 19

src/app/band/component/new-band-form/new-band-form.component.html, src/app/band/component/new-band-form/new-band-form.component.ts
Implementation of #29. Tested and works, do give feedback if you think I could do something better.
=> Feature 29

src/app/band/component/band-information/band-information.component.html, src/app/band/component/band-information/band-information.component.ts
Implementation of #41.  Give me feedback on this, particularly band-information.component.html line 9-16 if this can be done better, I think it definitely can be done better.
=> Feature 41

src/app/band/component/band-information/band-information.component.html, src/app/band/component/band-information/band-information.component.ts
Implementation of #43. Take a look and see if it is all good or if you have any suggestions.
=> Feature 43

src/app/band/component/band-information/band-information.component.html
=> Feature 45

src/app/app.component.html, src/app/app.component.ts, src/app/app.config.ts, src/app/band/component/band-information/band-information.component.ts, src/app/band/component/new-band-form/new-band-form.component.html, src/app/band/component/new-band-form/new-band-form.component.ts, src/app/service/notification.service.ts
Implementation of #49. Created an application level service in NotificationService and moved p-toast element to the App component, leading to successful implementation of the requested changes.
=> Feature 49

src/app/app.component.html, src/app/band/component/band-form/band-form.component.html, src/app/band/component/band-list/band-list.component.html
Centering of hero page and others should be bit better
=> Feature 34

README.md
A first draft that you can take a look and give feedback on.
=> Feature 39

src/app/band/component/band-list/band-list.component.html, src/app/band/component/band-list/band-list.component.ts
=> Feature 56

.github/workflows/frontend.yml, package.json, src/app/band/component/band-form/band-form.component.html, src/app/band/component/band-form/band-form.component.ts, src/app/pages/credits/credits.component.html
=> Feature 65

src/app/band/component/band-form/band-form.component.html, src/app/band/component/band-form/band-form.component.ts, src/app/band/service/band.service.ts
Implementation of #64. Hm any suggestions to make the text area field look better? Current appearance without outline looks odd to me.
=> Feature 64

src/app/band/component/band-form/band-form.component.ts
=> Feature 68

src/app/app.routes.ts, src/app/song/component/song-form/song-form.component.html, src/app/song/component/song-form/song-form.component.ts, src/app/song/component/song-list/song-list.component.html, src/app/song/component/song-list/song-list.component.ts, src/app/song/service/song.service.ts
Implementation of #71. Verified the form works and that you cannot create a song without a name.
=> Feature 71

src/app/app.routes.ts, src/app/song/component/song-form/song-form.component.html, src/app/song/component/song-form/song-form.component.ts, src/app/song/component/song-list/song-list.component.html, src/app/song/service/song.service.ts
=> Feature 74

src/app/song/component/song-form/song-form.component.html
=> Feature 76

src/app/band/component/band-form/band-form.component.html, src/app/band/component/band-form/band-form.component.ts
=> Feature 77
